name: test
on: [deployment_status]
jobs:
  production-deploy:
    if: github.event.deployment_status.created.state != 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Discord notification build start
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: '> pog `${{ github.event.deployment_status }}`'
